// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfwA7g5yxanlDglhcRV-xZ233vHwrd19g',
    appId: '1:774489257998:web:7ce58a00bfc2b05c7a645f',
    messagingSenderId: '774489257998',
    projectId: 'card-swift',
    authDomain: 'card-swift.firebaseapp.com',
    storageBucket: 'card-swift.firebasestorage.app',
    measurementId: 'G-1FP8CMDD3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj31_SOOIMnKzppSldEmPwHQDGKikdF74',
    appId: '1:774489257998:android:ac9d9272a8c3f89d7a645f',
    messagingSenderId: '774489257998',
    projectId: 'card-swift',
    storageBucket: 'card-swift.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwN3i2Yk9bG75j24fQ3NbicM5kAlhjqfc',
    appId: '1:774489257998:ios:f25719a1d8e85d3d7a645f',
    messagingSenderId: '774489257998',
    projectId: 'card-swift',
    storageBucket: 'card-swift.firebasestorage.app',
    iosBundleId: 'com.example.cardSwift',
  );
}
